trigger:
- main

pool:
  vmImage: 'ubuntu-latest'   # Microsoft-hosted agent

steps:
- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    Dockerfile: Dockerfile
    tags: |
      my-playwright:$(Build.BuildId)

- script: |
    docker run --rm -v $(System.DefaultWorkingDirectory)/test-results:/app/test-results my-playwright:$(Build.BuildId)
  displayName: Run Playwright tests in container

- task: PublishBuildArtifacts@1
  displayName: Publish test results
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/test-results'
    ArtifactName: 'playwright-results'
    publishLocation: 'Container'
